# binop_separator = "Front"
# blank_lines_lower_bound = 0
# blank_lines_upper_bound = 1
# brace_style = "AlwaysNextLine"
# color = "Auto"
# combine_control_expr = false
# comment_width = 131
# condense_wildcard_suffixes = true
# control_brace_style = "AlwaysNextLine"
# disable_all_formatting = false
# emit_mode = "Files"
# empty_item_single_line = false
# enum_discrim_align_threshold = 25
# error_on_line_overflow = false
# error_on_unformatted = false
# fn_single_line = false
# force_multiline_blocks = true
# format_macro_bodies = true
# format_macro_matchers = true
# format_strings = true
# hide_parse_errors = false
# ignore = []
# imports_indent = "Block"
# imports_layout = "Vertical"
# indent_style = "Block"
# inline_attribute_width = 0
# license_template_path = ""
# make_backup = true
# match_arm_blocks = true
# match_block_trailing_comma = true
# merge_imports = true
# normalize_comments = true
# normalize_doc_attributes = true 
# overflow_delimited_expr = false
# reorder_impl_items = true
# report_fixme = "Never"
# report_todo = "Never"
# required_version = "0.99.5"
# skip_children = false
# space_after_colon = true
# space_before_colon = true
# spaces_around_ranges = true
# struct_field_align_threshold = 30
# struct_lit_single_line = false
# trailing_comma = "Always"
# trailing_semicolon = true
# type_punctuation_density = "Wide"
# unstable_features = true
# where_single_line = false
# wrap_comments = true
edition = "2018"
fn_args_layout = "Vertical"
force_explicit_abi = true
hard_tabs = false
max_width = 131
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
tab_spaces = 4
use_field_init_shorthand = true
use_small_heuristics = "off"
use_try_shorthand = true
